// Generated by CoffeeScript 1.8.0
$(document).ready(function() {
  var add_marker, initialize;
  initialize = function() {
    var mapDim, mapDiv, mapOptions;
    mapDiv = document.getElementById("map-canvas");
    mapDim = {
      height: mapDiv.clientHeight,
      width: mapDiv.clientWidth
    };
    mapOptions = {
      center: {
        lat: 23.5,
        lng: 77
      },
      zoom: 4,
      panControl: true,
      zoomControl: true,
      scaleControl: true
    };
    return window.map = new google.maps.Map(mapDiv, mapOptions);
  };
  google.maps.event.addDomListener(window, "load", initialize);
  add_marker = function(title, lat, long) {
    var marker, myLatlng;
    myLatlng = new google.maps.LatLng(lat, long);
    marker = new google.maps.Marker({
      position: myLatlng,
      map: window.map,
      title: title
    });
    return google.maps.event.addListener(marker, "click", function() {
      debugger;
      $("#info-area").html(marker.title);
    });
  };
  return $("#plot-button").click(function() {
    var csv, lat, line, lines, long, split_content, title, _i, _len;
    csv = $("#plot-data")[0].value;
    lines = csv.split("\n");
    for (_i = 0, _len = lines.length; _i < _len; _i++) {
      line = lines[_i];
      split_content = line.split(",");
      lat = split_content[0];
      long = split_content[1];
      title = split_content[2];
      add_marker(title, lat, long);
    }
    return false;
  });
});
